networks:
  roboshop:
      driver: bridge
services:
  mongodb:
    build:
      context: .
      dockerfile: ./mongodb/Dockerfile
    image: mongodb:v1
    container_name: mongodb
  catalogue:
    build:
      context: .
      dockerfile: ./catalogue/Dockerfile
    image: catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  redis:
    image: redis:6.2
  user:
    build:
      context: .
      dockerfile: ./user/Dockerfile
    image: user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
  cart:
    build:
      context: .
      dockerfile: ./cart/Dockerfile
    image: cart:v1
    container_name: cart
    depends_on:
      - catalogue
      - redis
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    image: web:v1
    container_name: web
    ports:
      - "80:80"
    depends_on:
      - catalogue